AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: a simple loan application - Data Layer

Resources:
  LoanTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-LoanTable

Outputs:
  LoanTableOutput:
    Value: !Ref LoanTable
    Export:
      Name: !Join ["-", [!Ref "AWS::StackName", LoanTable]]
